### ISSUE TITLE
JSON from `resp.media` is not recognized

### ISSUE THREAD

**Issue by vytas7** [maxking/falcon-api-browse#5]
It seems this only works as expected if JSON is rendered via `resp.text`; however, the most idiomatic and succinct way of writing a JSON API is by leveraging [`req.get_media()` and `resp.media`](https://falcon.readthedocs.io/en/stable/api/media.html).

Test case used:
```python
import falcon
from falcon_api_browse import HTMLResponseMiddleware


class Hello:
    def on_get(self, req, resp):
        resp.media = {'message': 'Hello, World!', 'cool': True}


app = falcon.App(middleware=[HTMLResponseMiddleware()])
app.add_route('/hello', Hello())
```

**Comment by maxking** [comment]
@vytas7 I started off with resp.text initially as Mailman used that API, but I've migrated to using resp.media now. I can make the change here, but I was wondering what would be the right way to capture the response content regardless of the way it was set?

Would `response.render_body()` be the best API? It seems to take into account whether resp.text or resp.media is set and uses the appropriate media handler for serialization as well.

**Comment by vytas7** [comment]
Affirmative, `resp.render_body()` is probably the best option. At least I've gone that route in the ASGI tutorial; see [Caching Responses](https://falcon.readthedocs.io/en/latest/user/tutorial-asgi.html#caching-responses).

There is one caveat, however, that this approach currently doesn't support `resp.stream`. But maybe it's an acceptable tradeoff given that few would stream JSON?

**Comment by vytas7** [comment]
Note that `render_body()` is a new API in 3.0; so if you want to support Falcon 2.0, you'll need to shim this by reading back the `resp.data` property. However, given that you're referencing `resp.text` which is new in 3.0 anyway, maybe you can drop Falcon 2.0 support from `pyproject.toml`?

**Comment by maxking** [comment]
@vytas7 Thanks, I think that makes sense to drop support for 2.x since upgrade to 3.x hasn't been difficult, atleast in Mailman.

> There is one caveat, however, that this approach currently doesn't support resp.stream. But maybe it's an acceptable tradeoff given that few would stream JSON?

Yeah, I think we should be fine without resp.stream, we can come back to this later. YAGNI.
